branch-defaults:
  aws:
    environment: api-ml-production
deploy:
  artifact: Dockerrun.aws.json
global:
  application_name: API ML
  default_ec2_keyname: null
  default_platform: arn:aws:elasticbeanstalk:us-west-2::platform/Docker running on
    64bit Amazon Linux/2.7.4
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
